### ISSUE TITLE
Camera Snapping & Player Movement Inconsistency

### ISSUE THREAD

**Issue by gradyl16** [gradyl16/maze3#22]
### Problem

Player's controls for moving in consistent directions relative to any face of the cube changes depending on face traversal. Snapping the camera to bird's eye view may result in a dissonant perspective in compared to movement controls.

### Expected Behavior

Player's controls to navigate in any direction on the cube should be absolute in terms of a bird's eye view for that face.

### Steps to Reproduce

1. Traverse the cube from the starting face to the left face
2. Snap the camera (right-click)
3. Try to navigate

**Comment by peterPacho** [comment]
Should be fixed in new-player-movement branch.
